### ISSUE TITLE
error during prep

### ISSUE THREAD

**Issue by firmread** [wayspurrchen/moshy#2]
I run through exact same steps from the tutorial and got this error when trying to run `prep` command. 
```
$ moshy -m prep -i charlie.mp4 -o charlie.avi
I, [2016-01-09T20:51:27.428782 #53475]  INFO -- : [AV] Adding output parameter ["bf", 0]
I, [2016-01-09T20:51:27.428876 #53475]  INFO -- : [AV] Adding output parameter ["g", 600]
I, [2016-01-09T20:51:27.428905 #53475]  INFO -- : [AV] Adding output parameter ["b:v", "4196k"]
I, [2016-01-09T20:51:27.428999 #53475]  INFO -- : [AV] Running command: ffmpeg -i "charlie.mp4" -bf 0 -g 600 -b:v 4196k -y "charlie.avi"
/Users/firmread/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocaine-0.5.8/lib/cocaine/command_line.rb:82:in `run': Cocaine::CommandNotFoundError (Cocaine::CommandNotFoundError)
	from /Users/firmread/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/av-0.9.0/lib/av.rb:30:in `run'
	from /Users/firmread/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/av-0.9.0/lib/av/commands/base.rb:91:in `run'
	from /Users/firmread/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/moshy-1.0.2/lib/moshy/prep.rb:75:in `prep'
	from /Users/firmread/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/moshy-1.0.2/lib/moshy/prep.rb:58:in `cli'
	from /Users/firmread/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/moshy-1.0.2/bin/moshy:102:in `<top (required)>'
	from /Users/firmread/.rbenv/versions/2.3.0/bin/moshy:23:in `load'
	from /Users/firmread/.rbenv/versions/2.3.0/bin/moshy:23:in `<main>'
```

any suggestion on how to fix? Noted that I'm on ruby 2.3.0 on OS X 10.11.2. Thanks!

**Comment by wayspurrchen** [comment]
Hey @firmread, I haven't had a chance to look into this in detail yet, but can you try running this with Ruby ~2.0? Moshy ATM is only tested in Ruby ~2.0.

**Comment by Dimitraz** [comment]
I get the exact same issue, even when switching to an older version of Ruby

**Comment by wayspurrchen** [comment]
Thanks for the confirmation, @Dimitraz. I'll investigate this.

**Comment by wayspurrchen** [comment]
@Dimitraz @firmread I think the issue is that you may not have [ffmpeg](https://www.ffmpeg.org/) installed locally. The README mentions that you need to have it installed in order to use `prep` because it wraps it, although it is pretty unhelpful as to how to install it! Sorry about that. Try [installing ffmpeg](https://www.ffmpeg.org/download.html) for your OS and if the issue still persists, please let me know.

**Comment by Dimitraz** [comment]
@wayspurrchen Looks like I had forgotten to change the ffmpeg path! Works beautifully now, thank you!

**Comment by wayspurrchen** [comment]
:+1: Great to hear it!
