### ISSUE TITLE
I'm having serious issues understanding your example stuff.

### ISSUE THREAD

**Issue by EditFox** [wayspurrchen/moshy#3]
This is just about the only easy way to datamosh on pc, and I'm completely new to ruby.
I can't understand how I'm supposed to use your code in the readme, and I'm sooo lost.
If there could be example code or something, I'd probably be on the right track.

**Comment by wayspurrchen** [comment]
Hi @EvanCase54, you might find a tutorial I wrote to be a gentler introduction to datamoshing - http://forum.glitchet.com/t/tutorial-make-video-glitch-art-how-to-datamosh-in-plain-english/36 (although it doesn't address moshy use). This GitHub repo just shows you how to install the software and get started with it. Can you describe what you've tried, what you expected, and what happened instead?

You might also want to post in the [Glitch Artists Collective: Tool Time Facebook group](https://www.facebook.com/groups/GACToolTime/) - there are a number of people there who use moshy and could give you quick feedback on how to use it.
