### ISSUE TITLE
argument error

### ISSUE THREAD

**Issue by psyfae** [wayspurrchen/moshy#8]
hey there, i'm new to moshy & CLI. i know this project is quite old but hopefully it is still being used & maintained. i am looking for some pointers on encountering errors such as these

![image](https://user-images.githubusercontent.com/107946663/174855097-b78e23ed-c9d6-49d6-a23c-5ef490f63183.png)
![image](https://user-images.githubusercontent.com/107946663/174854676-6549dba7-9a7e-4cb2-9628-78771bd9945a.png)

i'm not sure what's going on here, any ideas?
sorry if it is a silly question, i'm new to this and not sure where to go for help.
thanks for reading, looking forward to hearing back.

**Comment by wayspurrchen** [comment]
Hi there, this is the same issue as #7 which I've now fixed. Please see the README for how to update to moshy `2.0.1` :)
